### ISSUE TITLE
Why can't this bot play a song for 3 minutes?

### ISSUE THREAD

**Issue by Naiml007** [RainyXeon/ByteBlaze#194]
**bot log**
```
2024-11-14T16:51:21.514Z | INFO      | CLUSTER_0 | TrackStart                   | Track Started in @ 𝗖𝗥𝗬𝗢𝗚𝗘𝗡 / 1240681432041521264
2024-11-14T16:51:22.414Z | ERROR     | CLUSTER_0 | PlayerException              | 'Player get exception \n' +
  "  op: 'event',\n" +
  "  type: 'TrackExceptionEvent',\n" +
  "  guildId: '1240681432041521264',\n" +
  '  track: {\n' +
  "    encoded: 'QAAA1QMAPVNreWZhbGwgfCBKYW1lcyBCb25kIHwgRGFuaWVsIENyYWlnIHwgNEsgfCBUaGVtZSBTb25nIHwgQWRlbGUACnNtYXJUVmlydXMAAAAAAARdMAALM3lCZ0x4Z3dTMVUAAQAraHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj0zeUJnTHhnd1MxVQEAMGh0dHBzOi8vaS55dGltZy5jb20vdmkvM3lCZ0x4Z3dTMVUvbXFkZWZhdWx0LmpwZwAAB3lvdXR1YmUAAAAAAAAAAA==',\n" +
  '    info: {\n' +
  "      identifier: '3yBgLxgwS1U',\n" +
  '      isSeekable: true,\n' +
  "      author: 'smarTVirus',\n" +
  '      length: 286000,\n' +
  '      isStream: false,\n' +
  '      position: 0,\n' +
  "      title: 'Skyfall | James Bond | Daniel Craig | 4K | Theme Song | Adele',\n" +
  "      uri: 'https://www.youtube.com/watch?v=3yBgLxgwS1U',\n" +
  "      sourceName: 'youtube',\n" +
  "      artworkUrl: 'https://i.ytimg.com/vi/3yBgLxgwS1U/mqdefault.jpg',\n" +
  '      isrc: null\n' +
  '    },\n' +
  '    pluginInfo: {},\n' +
  '    userData: {}\n' +
  '  },\n' +
  '  exception: {\n' +
  "    message: 'Please sign in',\n" +
  "    severity: 'suspicious',\n" +
  "    cause: 'com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Please sign in'\n" +
  '  }\n'
2024-11-14T16:51:22.423Z | INFO      | CLUSTER_0 | QueueEmpty                   | Queue Empty in @ 𝗖𝗥𝗬𝗢𝗚𝗘𝗡 / 1240681432041521264
2024-11-14T16:51:22.509Z | INFO      | CLUSTER_0 | PlayerDestroy                | Player Destroy in @ 𝗖𝗥𝗬𝗢𝗚𝗘𝗡 / 1240681432041521264
2024-11-14T16:52:48.915Z | INFO      | CLUSTER_0 | CommandManager | Interaction | [247] used by zmr48105 from 𝗖𝗥𝗬𝗢𝗚𝗘𝗡 (1240681432041521264)
2024-11-14T16:52:52.915Z | INFO      | CLUSTER_0 | PlayerCreate                 | Player Created in @ 𝗖𝗥𝗬𝗢𝗚𝗘𝗡 / 1240681432041521264
2024-11-14T16:53:03.316Z | INFO      | CLUSTER_0 | CommandManager | Interaction | [language] used by zmr48105 from 𝗖𝗥𝗬𝗢𝗚𝗘𝗡 (1240681432041521264)
2024-11-14T16:53:18.828Z | INFO      | CLUSTER_0 | CommandManager | Interaction | [setup] used by zmr48105 from 𝗖𝗥𝗬𝗢𝗚𝗘𝗡 (1240681432041521264)
2024-11-14T16:54:54.117Z | INFO      | CLUSTER_0 | CommandManager | Interaction | [play] used by zmr48105 from 𝗖𝗥𝗬𝗢𝗚𝗘𝗡 (1240681432041521264)
2024-11-14T16:54:55.916Z | INFO      | CLUSTER_0 | TrackStart                   | Track Started in @ 𝗖𝗥𝗬𝗢𝗚𝗘𝗡 / 1240681432041521264
2024-11-14T16:54:56.661Z | ERROR     | CLUSTER_0 | PlayerException              | 'Player get exception \n' +
  "  op: 'event',\n" +
  "  type: 'TrackExceptionEvent',\n" +
  "  guildId: '1240681432041521264',\n" +
  '  track: {\n' +
  "    encoded: 'QAAA0gMAN0thdGUgQnVzaCAtIFJ1bm5pbmcgVXAgVGhhdCBIaWxsIC0gT2ZmaWNpYWwgTXVzaWMgVmlkZW8ADUthdGVCdXNoTXVzaWMAAAAAAASEQAALd3A0M09kdEFBa00AAQAraHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj13cDQzT2R0QUFrTQEAMGh0dHBzOi8vaS55dGltZy5jb20vdmkvd3A0M09kdEFBa00vbXFkZWZhdWx0LmpwZwAAB3lvdXR1YmUAAAAAAAAAAA==',\n" +
  '    info: {\n' +
  "      identifier: 'wp43OdtAAkM',\n" +
  '      isSeekable: true,\n' +
  "      author: 'KateBushMusic',\n" +
  '      length: 296000,\n' +
  '      isStream: false,\n' +
  '      position: 0,\n' +
  "      title: 'Kate Bush - Running Up That Hill - Official Music Video',\n" +
  "      uri: 'https://www.youtube.com/watch?v=wp43OdtAAkM',\n" +
  "      sourceName: 'youtube',\n" +
  "      artworkUrl: 'https://i.ytimg.com/vi/wp43OdtAAkM/mqdefault.jpg',\n" +
  '      isrc: null\n' +
  '    },\n' +
  '    pluginInfo: {},\n' +
  '    userData: {}\n' +
  '  },\n' +
  '  exception: {\n' +
  "    message: 'Please sign in',\n" +
  "    severity: 'suspicious',\n" +
  "    cause: 'com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Please sign in'\n" +
  ```
  **Lavalink**
  ```
  3AsmarTVirus+-+Skyfall+%7C+James+Bond+%7C+Daniel+Craig+%7C+4K+%7C+Theme+Song+%7C+Adele, client=103.245.111.89
2024-11-14T11:51:21.457-05:00  INFO 27 --- [  XNIO-1 task-3] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/zt0kwcr0ti1kchj0/players/1240681432041521264?noReplace=false, client=103.245.111.89, payload={"track":{"encoded":"QAAA1QMAPVNreWZhbGwgfCBKYW1lcyBCb25kIHwgRGFuaWVsIENyYWlnIHwgNEsgfCBUaGVtZSBTb25nIHwgQWRlbGUACnNtYXJUVmlydXMAAAAAAARdMAALM3lCZ0x4Z3dTMVUAAQAraHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj0zeUJnTHhnd1MxVQEAMGh0dHBzOi8vaS55dGltZy5jb20vdmkvM3lCZ0x4Z3dTMVUvbXFkZWZhdWx0LmpwZwAAB3lvdXR1YmUAAAAAAAAAAA==","length":286000},"replaceCurrent":false,"volume":100}
2024-11-14T11:51:22.347-05:00  WARN 27 --- [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Suspicious exception for playback of 3yBgLxgwS1U
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Please sign in
        at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:102) ~[youtube-plugin-1.8.3.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:101) ~[lavaplayer-2.1.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:330) ~[lavaplayer-2.1.1.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]
2024-11-14T11:51:22.463-05:00  INFO 27 --- [  XNIO-1 task-3] l.server.io.RequestLoggingFilter         : DELETE /v4/sessions/zt0kwcr0ti1kchj0/players/1240681432041521264, client=103.245.111.89
2024-11-14T11:51:48.218-05:00  INFO 27 --- [ool-12-thread-1] lavalink.server.io.SocketContext         : Shutting down 0 playing players.
2024-11-14T11:52:50.465-05:00  INFO 27 --- [  XNIO-1 task-3] l.server.io.RequestLoggingFilter         : GET /v4/stats, client=103.245.111.89
2024-11-14T11:52:52.829-05:00  INFO 27 --- [  XNIO-1 task-3] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/zt0kwcr0ti1kchj0/players/1240681432041521264?noReplace=false, client=103.245.111.89, payload={"voice":{"token":"f716cbf301979f6d","endpoint":"singapore11120.discord.media:443","sessionId":"21bb33b248fb2e229efe3770917e8294"}}
2024-11-14T11:54:45.346-05:00  INFO 27 --- [  XNIO-1 task-3] l.server.io.RequestLoggingFilter         : GET /v4/stats, client=103.245.111.89
2024-11-14T11:54:45.547-05:00  INFO 27 --- [  XNIO-1 task-3] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "ytsearch:yorushika"
2024-11-14T11:54:46.014-05:00  INFO 27 --- [  XNIO-1 task-3] lavalink.server.player.AudioLoader       : Loaded playlist Search results for: yorushika
2024-11-14T11:54:46.016-05:00  INFO 27 --- [  XNIO-1 task-3] l.server.io.RequestLoggingFilter         : GET /v4/loadtracks?identifier=ytsearch%3Ayorushika, client=103.245.111.89
2024-11-14T11:54:50.554-05:00  INFO 27 --- [  XNIO-1 task-3] l.server.io.RequestLoggingFilter         : GET /v4/stats, client=103.245.111.89
2024-11-14T11:54:50.748-05:00  INFO 27 --- [  XNIO-1 task-3] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "ytsearch:r"
2024-11-14T11:54:51.115-05:00  INFO 27 --- [  XNIO-1 task-3] lavalink.server.player.AudioLoader       : Loaded playlist Search results for: r
2024-11-14T11:54:51.117-05:00  INFO 27 --- [  XNIO-1 task-3] l.server.io.RequestLoggingFilter         : GET /v4/loadtracks?identifier=ytsearch%3Ar, client=103.245.111.89
2024-11-14T11:54:54.552-05:00  INFO 27 --- [  XNIO-1 task-3] l.server.io.RequestLoggingFilter         : GET /v4/stats, client=103.245.111.89
2024-11-14T11:54:54.649-05:00  INFO 27 --- [  XNIO-1 task-3] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "ytsearch:running up that hill"
2024-11-14T11:54:54.751-05:00  INFO 27 --- [  XNIO-1 task-2] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "ytsearch:running up that hill"
2024-11-14T11:54:55.175-05:00  INFO 27 --- [  XNIO-1 task-3] lavalink.server.player.AudioLoader       : Loaded playlist Search results for: running up that hill
2024-11-14T11:54:55.177-05:00  INFO 27 --- [  XNIO-1 task-3] l.server.io.RequestLoggingFilter         : GET /v4/loadtracks?identifier=ytsearch%3Arunning+up+that+hill, client=103.245.111.89
2024-11-14T11:54:55.700-05:00  INFO 27 --- [  XNIO-1 task-2] lavalink.server.player.AudioLoader       : Loaded playlist Search results for: running up that hill
2024-11-14T11:54:55.702-05:00  INFO 27 --- [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : GET /v4/loadtracks?identifier=ytsearch%3Arunning+up+that+hill, client=103.245.111.89
2024-11-14T11:54:55.866-05:00  INFO 27 --- [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/zt0kwcr0ti1kchj0/players/1240681432041521264?noReplace=false, client=103.245.111.89, payload={"track":{"encoded":"QAAA0gMAN0thdGUgQnVzaCAtIFJ1bm5pbmcgVXAgVGhhdCBIaWxsIC0gT2ZmaWNpYWwgTXVzaWMgVmlkZW8ADUthdGVCdXNoTXVzaWMAAAAAAASEQAALd3A0M09kdEFBa00AAQAraHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj13cDQzT2R0QUFrTQEAMGh0dHBzOi8vaS55dGltZy5jb20vdmkvd3A0M09kdEFBa00vbXFkZWZhdWx0LmpwZwAAB3lvdXR1YmUAAAAAAAAAAA==","length":296000},"replaceCurrent":false,"volume":100}
2024-11-14T11:54:56.611-05:00  WARN 27 --- [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Suspicious exception for playback of wp43OdtAAkM
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Please sign in
        at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:102) ~[youtube-plugin-1.8.3.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:101) ~[lavaplayer-2.1.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:330) ~[lavaplayer-2.1.1.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]
2024-11-14T11:54:58.353-05:00  INFO 27 --- [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : DELETE /v4/sessions/zt0kwcr0ti1kchj0/players/1240681432041521264, client=103.245.111.89
2024-11-14T11:54:59.653-05:00  INFO 27 --- [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : GET /v4/stats, client=103.245.111.89
2024-11-14T11:55:01.731-05:00  INFO 27 --- [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/zt0kwcr0ti1kchj0/players/1240681432041521264?noReplace=false, client=103.245.111.89, payload={"voice":{"token":"4598e80ab5f5e315","endpoint":"singapore11120.discord.media:443","sessionId":"21bb33b248fb2e229efe3770917e8294"}}

  ```

**Comment by RainyXeon** [comment]
U can try update YouTube source and enable oauth on application.yml then

Fyi, please read the readme
https://github.com/lavalink-devs/youtube-source

**Comment by Naiml007** [comment]
tnx 

https://github.com/LucasB25/lavalink-server
